// Attribution footer appended to bodies created by safe outputs (gh-aw's `footer`).
//
// Default ON (good practice + attribution for AI-generated GitHub content). The
// author can customize the template with `--footer-text` or disable it with
// `--no-footer` (or `--footer=false`). Placeholders are resolved host-side from the
// Actions environment.

/** @returns {boolean} whether the footer is enabled */
export function footerEnabled(config = {}) {
  if (config.noFooter) return false;
  if (config.footer === "false" || config.footer === false) return false;
  return true;
}

/**
 * Render the footer text (no leading separator). Empty string when disabled.
 * @param {{footer?: string|boolean, noFooter?: boolean, footerText?: string}} config
 * @param {NodeJS.ProcessEnv} [env]
 * @returns {string}
 */
export function renderFooter(config = {}, env = process.env) {
  if (!footerEnabled(config)) return "";
  const workflow = env.GITHUB_WORKFLOW || "agentic workflow";
  const repo = env.GITHUB_REPOSITORY || "";
  const server = env.GITHUB_SERVER_URL || "https://github.com";
  const runId = env.GITHUB_RUN_ID || "";
  const runUrl = repo && runId ? `${server}/${repo}/actions/runs/${runId}` : server;
  const template = config.footerText || "> Generated by [{workflow}]({run_url})";
  return template
    .replace(/\{workflow\}/g, workflow)
    .replace(/\{run_url\}/g, runUrl)
    .replace(/\{repo\}/g, repo);
}

/**
 * Append the footer to a body (with a blank-line separator) unless disabled.
 * @param {string} body
 * @param {object} config
 * @param {NodeJS.ProcessEnv} [env]
 * @returns {string}
 */
export function withFooter(body, config = {}, env = process.env) {
  const footer = renderFooter(config, env);
  if (!footer) return body;
  return `${body}\n\n${footer}`;
}
